import React, { useEffect, useState } from 'react'
import { AdminLayout, type AdminSidebarSection } from '../../components/AdminLayout'
import { Badge, Button, EmptyState, Input, PageLoader, Select, showToast } from '../../components/ui'
import { ADMIN_AI_PROCESSING_PATH, ADMIN_BILLING_PATH, ADMIN_LOGIN_PATH, ADMIN_OVERVIEW_PATH } from '../../lib/adminRoutes'
import { unwrapApiData } from '../../lib/apiResponse'
import { signOutAndClearSessions } from '../../lib/auth'
import { invokeApiFunction } from '../../lib/functionApi'
import { getSafeUser } from '../../lib/identityClient'

type Overview = { products:any[]; prices:any[]; plans:any[]; subscriptions:any[]; invoices:any[]; payments:any[]; organizations:any[]; settings:any; metrics:{mrr_minor:number;arr_minor:number;active_subscriptions:number;trials:number;past_due:number;suspended:number;outstanding_minor:number} }
const sections: AdminSidebarSection[]=[{id:'dashboard',label:'Dashboard',href:ADMIN_OVERVIEW_PATH},{id:'billing-overview',label:'Overview',href:ADMIN_BILLING_PATH},{id:'products',label:'Products'},{id:'plans',label:'Plans'},{id:'organizations',label:'Organizations'},{id:'subscriptions',label:'Subscriptions'},{id:'invoices',label:'Invoices'},{id:'payments',label:'Payments'},{id:'settings',label:'Settings'},{id:'ai-processing',label:'AI & Processing',href:ADMIN_AI_PROCESSING_PATH}]
const panel:React.CSSProperties={background:'#fff',border:'1px solid var(--admin-border)',borderRadius:12,padding:16,boxShadow:'var(--admin-shadow)'}
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:12}
const money=(minor:number,currency='NGN')=>new Intl.NumberFormat('en-NG',{style:'currency',currency,maximumFractionDigits:0}).format((minor||0)/100)

export default function AdminBilling(){
  const [data,setData]=useState<Overview|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [viewer,setViewer]=useState<string|null>(null); const [search,setSearch]=useState(''); const [saving,setSaving]=useState('')
  async function load(){setLoading(true);setError('');try{const result=await invokeApiFunction<unknown>('admin-billing',{method:'GET'},'Billing data could not be loaded right now.');const unwrapped=unwrapApiData<Overview>(result);setData((unwrapped.found?unwrapped.value:result) as Overview)}catch(error){setError(error instanceof Error?error.message:'Billing data could not be reached right now. Check your connection and try again.')}finally{setLoading(false)}}
  useEffect(()=>{void getSafeUser().then(user=>setViewer(user?.email??null));void load()},[])
  async function action(body:any){setSaving(body.product_id??body.subscription_id??body.action);try{await invokeApiFunction('admin-billing',{body},'Billing configuration could not be saved right now.');showToast('Billing configuration saved.','success');await load()}catch(error){showToast(error instanceof Error?error.message:'Billing configuration could not be reached right now. Check your connection and try again.','error')}finally{setSaving('')}}
  async function logout(){await signOutAndClearSessions();window.location.assign(ADMIN_LOGIN_PATH)}
  if(loading&&!data)return <PageLoader label="Loading billing and subscriptions..." />
  return <AdminLayout activeSection="billing-overview" darkMode={false} notificationsCount={data?.metrics.past_due??0} onLogout={()=>void logout()} onSearchChange={setSearch} onToggleTheme={()=>undefined} searchQuery={search} sections={sections} title="Billing & Subscriptions" userName={viewer}>
    {error&&<div style={{...panel,color:'#b91c1c'}}>{error}<Button onClick={()=>void load()}>Retry</Button></div>}
    {data&&<div style={{display:'grid',gap:18}}>
      <section id="billing-overview"><div style={grid}>{[['Monthly Recurring Revenue',money(data.metrics.mrr_minor)],['Annual Recurring Revenue',money(data.metrics.arr_minor)],['Active Subscriptions',data.metrics.active_subscriptions],['Organizations on Trial',data.metrics.trials],['Past Due / Grace',data.metrics.past_due],['Outstanding Invoices',money(data.metrics.outstanding_minor)]].map(([label,value])=><article style={panel} key={label}><div style={{fontSize:11,color:'var(--admin-muted)',fontWeight:700}}>{label}</div><div style={{fontSize:23,fontWeight:800,marginTop:8}}>{value}</div></article>)}</div></section>
      <section id="products" style={panel}><h2>Products & public pricing</h2><p style={{color:'var(--admin-muted)',fontSize:12}}>Configure availability and pricing contexts. Public pricing reads this catalog; amounts are never hardcoded in the pricing page.</p><div style={{display:'grid',gap:10}}>{data.products.filter(p=>!search||p.name.toLowerCase().includes(search.toLowerCase())).map(product=><ProductRow key={product.id} product={product} prices={data.prices.filter(price=>price.product_id===product.id)} saving={saving} onSave={action}/>)}</div></section>
      <section id="plans" style={panel}><h2>Plans</h2>{data.plans.length?<div style={grid}>{data.plans.map(plan=><article className="commercial-card" key={plan.id}><h3>{plan.name}</h3><p>{money(plan.monthly_price_minor,plan.currency)} monthly · {plan.trial_days} day trial</p></article>)}</div>:<EmptyState icon={<span>₦</span>} title="No plans configured" description="Create small, medium, large, enterprise, or custom plans after the billing migration is applied."/>}</section>
      <section id="organizations" style={panel}><h2>Organization subscriptions</h2>{data.subscriptions.length?<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:12}}><thead><tr>{['Organization','Plan','Status','Cycle','Next billing','Outstanding','Action'].map(h=><th key={h} style={{padding:10,textAlign:'left',borderBottom:'1px solid var(--admin-border)'}}>{h}</th>)}</tr></thead><tbody>{data.subscriptions.map(subscription=><tr key={subscription.id}><td style={{padding:10}}>{subscription.organization?.name}</td><td>{subscription.plan?.name??'Custom'}</td><td><Badge>{subscription.status}</Badge></td><td>{subscription.billing_cycle}</td><td>{subscription.next_billing_at?new Date(subscription.next_billing_at).toLocaleDateString():'-'}</td><td>{money(subscription.outstanding_minor,subscription.currency)}</td><td><Select value={subscription.status} options={['trial','active','past_due','grace_period','restricted','suspended','cancelled','expired'].map(status=>({value:status,label:status}))} onChange={event=>void action({action:'set_subscription_status',subscription_id:subscription.id,status:event.target.value})} disabled={saving===subscription.id}/></td></tr>)}</tbody></table></div>:<EmptyState icon={<span>◎</span>} title="No organization subscriptions" description="Subscriptions will appear here after organizations are enrolled."/>}</section>
      <section id="invoices" style={panel}><h2>Invoices & payments</h2><p>{data.invoices.length} invoices · {data.payments.length} payments recorded.</p></section>
      <section id="settings" style={panel}><h2>Progressive restriction policy</h2><p style={{color:'var(--admin-muted)',fontSize:12}}>Default trial: {data.settings.default_trial_days} days · Grace period: {data.settings.grace_period_days} days · Critical clinical workflows remain available during progressive billing restrictions.</p></section>
    </div>}
  </AdminLayout>
}

function ProductRow({product,prices,saving,onSave}:{product:any;prices:any[];saving:string;onSave:(body:any)=>Promise<void>}){
  const [form,setForm]=useState(product); const primaryPrice=prices[0]; const [price,setPrice]=useState({product_id:product.id,context:primaryPrice?.context??(product.available_addon?'addon':'standalone'),visibility:primaryPrice?.visibility??'contact_sales',amount_minor:primaryPrice?.amount_minor??'',currency:primaryPrice?.currency??'NGN',unit:primaryPrice?.unit??'',active:true})
  return <div style={{...panel,boxShadow:'none'}}><div style={{display:'grid',gridTemplateColumns:'minmax(180px,1fr) repeat(3,minmax(120px,.6fr)) auto',gap:9,alignItems:'end'}}><Input label="Product" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><Select label="Status" value={form.status} options={['active','coming_soon','draft','retired'].map(value=>({value,label:value}))} onChange={e=>setForm({...form,status:e.target.value})}/><Select label="Pricing" value={price.visibility} options={[['fixed','Fixed price'],['starting_from','Starting from'],['contact_sales','Contact sales'],['custom_quote','Custom quote'],['hidden','Hidden']].map(([value,label])=>({value,label}))} onChange={e=>setPrice({...price,visibility:e.target.value})}/><Input label="Amount (minor units)" type="number" value={price.amount_minor} onChange={e=>setPrice({...price,amount_minor:e.target.value})}/><Button loading={saving===product.id} onClick={async()=>{await onSave({action:'save_product',product_id:product.id,product:form});await onSave({action:'save_price',price:{...price,amount_minor:price.amount_minor===''?null:Number(price.amount_minor)}})}}>Save</Button></div></div>
}
