import React,{useCallback,useEffect,useState}from'react'
import{Button,EmptyState,PageLoader,showToast}from'../../../components/ui'
import type{MigrationProjectAccess}from'../domain'
import{listProcessing,type ProcessingFolder}from'../api/migrationProcessing'
import{getMatches,matchingCommand,type MatchCandidate,type MatchDecision}from'../api/migrationMatching'
import{MigrationStatusBadge}from'./MigrationStatusBadge'
export function MatchingWorkspace({project}:{project:MigrationProjectAccess}){
 const[folders,setFolders]=useState<ProcessingFolder[]>([]),[folderId,setFolderId]=useState<string|null>(null),[candidates,setCandidates]=useState<MatchCandidate[]>([]),[decision,setDecision]=useState<MatchDecision|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{setLoading(true);try{const result=await listProcessing<ProcessingFolder>(project.id,'folders');setFolders(result.data);const id=folderId??result.data[0]?.id??null;setFolderId(id);if(id){const matches=await getMatches(project.id,id);setCandidates(matches.data.candidates);setDecision(matches.data.decision)}}catch(e){showToast(e instanceof Error?e.message:'Matching queue could not be loaded.','error')}finally{setLoading(false)}},[project.id,folderId])
 useEffect(()=>{void load()},[project.id])
 const run=async(action:string,payload:Record<string,unknown>={})=>{if(!folderId)return;setBusy(true);try{await matchingCommand(project.id,folderId,action,payload);showToast(action==='generate'?'Candidates refreshed.':'Match decision recorded.','success');await load()}catch(e){showToast(e instanceof Error?e.message:'Matching action failed.','error')}finally{setBusy(false)}}
 if(loading)return <PageLoader label="Loading patient matching..."/>
 if(!folderId)return <EmptyState icon={<span>ID</span>} title="No folders ready for matching" description="Validated source folders appear here before import."/>
 return <><div className="migrate-pagehead"><div><h1>Patient matching</h1><p>Identifier-qualified, explainable candidates. No uncertain identity is auto-merged.</p></div><Button disabled={busy||!!decision} onClick={()=>void run('generate')}>Find candidates</Button></div>
 <div className="migrate-validation"><aside className="migrate-card migrate-section">{folders.map(folder=><button key={folder.id} className="migrate-attention" style={{width:'100%',border:0,textAlign:'left',background:folder.id===folderId?'var(--soft-blue)':'transparent'}} onClick={()=>{setFolderId(folder.id);setCandidates([]);setDecision(null);void getMatches(project.id,folder.id).then(r=>{setCandidates(r.data.candidates);setDecision(r.data.decision)})}}><strong className="migrate-mono">{folder.folder_reference}</strong></button>)}</aside>
 <section className="migrate-card migrate-section">{decision?<EmptyState icon={<span>✓</span>} title="Match decision recorded" description={decision.decision.replace(/_/g,' ')} action={<Button variant="danger" disabled={busy} onClick={()=>void run('revoke',{reason:'Operator requested match correction'})}>Open correction</Button>}/>:candidates.length===0?<EmptyState icon={<span>?</span>} title="No qualified candidate" description="Generate candidates, create a pending identity request, defer, or escalate." action={<div className="migrate-actions"><Button disabled={busy} onClick={()=>void run('decide',{decision:'create_new_pending'})}>Request new identity</Button><Button variant="secondary" disabled={busy} onClick={()=>void run('decide',{decision:'review_later'})}>Review later</Button><Button variant="danger" disabled={busy} onClick={()=>void run('decide',{decision:'escalate'})}>Escalate</Button></div>}/>:candidates.map(candidate=><div className="migrate-attention" key={candidate.id}><div><strong>{candidate.masked_patient_snapshot.full_name}</strong><small><span className="migrate-mono">{candidate.masked_patient_snapshot.hid_code}</span> · DOB {candidate.masked_patient_snapshot.dob||'unknown'} · {candidate.masked_patient_snapshot.phone||'phone masked'}</small><small>Identifier {candidate.features.identifier?'agrees':'unknown'} · name {candidate.features.name?'agrees':'differs'} · DOB {candidate.features.dob?'agrees':'differs'}</small></div><MigrationStatusBadge status={`${candidate.band} ${Math.round(candidate.score*100)}%`} positive={candidate.band==='exact'||candidate.band==='strong'}/><Button disabled={busy} onClick={()=>void run('decide',{decision:'link_existing',candidate_id:candidate.id})}>Link patient</Button></div>)}</section></div></>
}
