import React,{useCallback,useEffect,useState}from'react'
import{Button,EmptyState,PageLoader,showToast}from'../../../components/ui'
import type{MigrationProjectAccess}from'../domain'
import{listReviewTasks,reviewCommand,type QaTask,type ValidationTask}from'../api/migrationReview'
export function ReviewWorkspace({project,type}:{project:MigrationProjectAccess;type:'validation'|'qa'}){
 const[tasks,setTasks]=useState<Array<ValidationTask|QaTask>>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[edits,setEdits]=useState<Record<string,string>>({})
 const load=useCallback(async()=>{setLoading(true);try{const result=await listReviewTasks<ValidationTask|QaTask>(project.id,type);setTasks(result.data);setSelected(current=>result.data.some(task=>task.id===current)?current:result.data[0]?.id??null)}catch(error){showToast(error instanceof Error?error.message:'Review queue could not be loaded.','error')}finally{setLoading(false)}},[project.id,type])
 useEffect(()=>{void load()},[load])
 const wrapper=tasks.find(task=>task.id===selected),task=type==='qa'?(wrapper as QaTask|undefined)?.validation_task:wrapper as ValidationTask|undefined
 useEffect(()=>{setEdits(task?Object.fromEntries(Object.entries(task.extraction.fields).map(([name,field])=>[name,String(field.value??'')])):{})},[task?.extraction.id])
 const run=async(action:string)=>{if(!wrapper)return;setBusy(true);try{const corrected_fields=task?Object.fromEntries(Object.entries(task.extraction.fields).map(([name,field])=>[name,{...field,value:edits[name]??''}])):{};await reviewCommand(project.id,type,wrapper.id,action,action==='corrected'?{corrected_fields}:{});showToast(action==='claim'?'Task claimed.':`Decision recorded: ${action}.`,'success');await load()}catch(error){showToast(error instanceof Error?error.message:'Review action failed.','error')}finally{setBusy(false)}}
 if(loading)return <PageLoader label={`Loading ${type} queue...`}/>
 if(!task)return <EmptyState icon={<span>OK</span>} title={`No ${type} tasks`} description="There are no claimable tasks in this project queue."/>
 const claimed=wrapper!.status==='claimed'
 return <><div className="migrate-pagehead"><div><h1>{type==='qa'?'Quality assurance':'Human validation'}</h1><p>Exclusive leases and append-only, source-linked decisions.</p></div></div><div className="migrate-validation">
  <aside className="migrate-card migrate-section">{tasks.map(item=>{const row=type==='qa'?(item as QaTask).validation_task:item as ValidationTask;return <button key={item.id} onClick={()=>setSelected(item.id)} className="migrate-attention" style={{width:'100%',border:0,background:item.id===selected?'var(--soft-blue)':'transparent',textAlign:'left'}}><div><strong>{row.document.title||row.document.document_reference}</strong><small>{type==='qa'?(item as QaTask).sampling_reason:row.status}</small></div></button>})}</aside>
  <section className="migrate-card migrate-section"><div className="migrate-section-head"><h2>{task.document.title||task.document.document_reference}</h2><span className="migrate-mono">{task.extraction.overall_confidence==null?'-':`${Math.round(task.extraction.overall_confidence*100)}%`}</span></div>
  {Object.entries(task.extraction.fields).map(([name,field])=><div className="migrate-attention" key={name}><div style={{flex:1}}><strong>{name.replace(/_/g,' ')}</strong>{type==='validation'&&claimed?<input aria-label={name.replace(/_/g,' ')} value={edits[name]??''} onChange={event=>setEdits(current=>({...current,[name]:event.target.value}))}/>:<small>{String(field.value??'')}</small>}<small>{field.source_spans.map(span=>`page ${span.page_id.slice(0,8)} [${span.start}:${span.end}]`).join(', ')}</small></div><span className="migrate-mono">{field.confidence==null?'-':`${Math.round(field.confidence*100)}%`}</span></div>)}
  <div className="migrate-actions">{!claimed?<Button disabled={busy} onClick={()=>void run('claim')}>Claim task</Button>:type==='validation'?<><Button disabled={busy} onClick={()=>void run('approved')}>Approve unchanged</Button><Button variant="secondary" disabled={busy} onClick={()=>void run('corrected')}>Approve corrections</Button><Button variant="secondary" disabled={busy} onClick={()=>void run('sent_back')}>Send back</Button><Button variant="danger" disabled={busy} onClick={()=>void run('rejected')}>Reject</Button></>:<><Button disabled={busy} onClick={()=>void run('approved')}>QA approve</Button><Button variant="secondary" disabled={busy} onClick={()=>void run('returned')}>Return</Button><Button variant="danger" disabled={busy} onClick={()=>void run('escalated')}>Escalate</Button></>}</div>
  </section></div></>
}
