import React from 'react'
import { Link, useParams } from 'react-router-dom'
import { CommercialLayout } from '../features/commercial/CommercialLayout'
import { products, solutions } from '../features/commercial/catalog'
import { PROVIDER_ACCESS_HREF } from '../lib/providerAccess'

export default function CommercialProducts() {
  const { slug } = useParams()
  const product = products.find(item => item.slug === slug)
  if (!product) return <CommercialLayout><main><section className="commercial-hero"><div className="commercial-shell"><div className="commercial-eyebrow">One connected ecosystem</div><h1>Products built around one health identity.</h1><p>Use HID as a complete hospital operating environment, activate individual standalone products, or connect existing healthcare software through HID APIs.</p><div className="commercial-grid">{products.map(item => <article className="commercial-card" key={item.slug}><div className="commercial-badges">{item.badges.map(badge => <span className="commercial-badge" key={badge}>{badge}</span>)}</div><h3>{item.name}</h3><p>{item.description}</p><Link className="commercial-button" to={`/products/${item.slug}`}>Explore {item.name}</Link></article>)}</div></div></section><section className="commercial-section soft"><div className="commercial-shell"><h2>Built for every part of healthcare.</h2><div className="commercial-grid">{solutions.map(([name, mapped]) => <article className="commercial-card" key={name}><h3>{name}</h3><p>{mapped.join(' · ')}</p></article>)}</div></div></section></main></CommercialLayout>
  return <CommercialLayout><main><section className="commercial-hero"><div className="commercial-shell"><div className="commercial-eyebrow">{product.eyebrow}</div><h1>{product.headline}</h1><p>{product.description}</p><div className="commercial-badges">{product.badges.map(badge => <span className="commercial-badge" key={badge}>{badge}</span>)}</div><div className="commercial-actions">{product.slug === 'ehr' && <Link className="commercial-button primary" to="/configure-ehr">Configure Your HID EHR</Link>}{product.slug === 'migrate' && <a className="commercial-button primary" href="https://migrate.healthidentitydirectory.com/">Open HID Migrate</a>}{['ehr', 'migrate', 'laboratory', 'pharmacy'].includes(product.slug) && <Link className="commercial-button primary" to={`/provider/apply?product=${product.slug}`}>Apply as an organization</Link>}<a className="commercial-button" href={PROVIDER_ACCESS_HREF}>Provider sign in</a><a className="commercial-button" href={`mailto:hello@healthidentitydirectory.com?subject=${encodeURIComponent(product.name + ' demo')}`}>Book a Demo</a></div></div></section><section className="commercial-section"><div className="commercial-shell"><h2>Designed for real healthcare workflows.</h2><div className="commercial-grid">{product.capabilities.map(capability => <article className="commercial-card" key={capability}><h3>{capability}</h3><p>Connected to the HID ecosystem with role-aware access and auditable workflows.</p></article>)}</div></div></section>{product.slug === 'migrate' && <section className="commercial-section soft"><div className="commercial-shell"><h2>Governed OCR operations, not a duplicate migration system.</h2><p className="commercial-lead">Secured Document Reference → Authorized OCR Job → Extraction Metadata → Validation State → Eligible Retry or Publication Handoff → Contextual Review</p><a className="commercial-button primary" href="https://migrate.healthidentitydirectory.com/">Open HID Migrate</a></div></section>}</main></CommercialLayout>
}
